#!/usr/bin/env python3
"""Extract zynq_ultra_ps_e CONFIG.* properties from a Vivado .bd JSON
and regenerate scripts/ps_preset.tcl.

Usage:
  python scripts/extract_ps_preset.py path/to/design.bd

Pass the factory design_1.bd path as argv[1]. There is no host-specific default.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

SCRIPT_DIR = Path(__file__).resolve().parent
OUT_TCL = SCRIPT_DIR / "ps_preset.tcl"

HEADER = """\
# =============================================================================
# PS (zynq_ultra_ps_e) preset for NetSec-Accel-ZU4EV
#
# Source : factory board_test design_1.bd
# Vivado : 2020.1
# Part   : xczu4ev-sfvc784-1-i
#
# Regenerated by: scripts/extract_ps_preset.py
#
# Usage (in Vivado Tcl, after creating the PS cell):
#   create_bd_cell -type ip -vlnv xilinx.com:ip:zynq_ultra_ps_e:3.3 zynq_ultra_ps_e_0
#   source scripts/ps_preset.tcl
#   apply_ps_preset [get_bd_cells zynq_ultra_ps_e_0]
# =============================================================================
"""

# Keep each set_property -dict list manageable for Vivado Tcl.
CHUNK_SIZE = 80


def find_ps_component(design: dict) -> tuple[str, dict]:
    """Return (instance_name, component_dict) for zynq_ultra_ps_e."""
    components = design.get("design", design).get("components", {})
    if not isinstance(components, dict):
        raise RuntimeError("BD JSON has no design.components object")

    for name, comp in components.items():
        if not isinstance(comp, dict):
            continue
        vlnv = str(comp.get("vlnv") or comp.get("vlNV") or "")
        if "zynq_ultra_ps_e" in vlnv or name.startswith("zynq_ultra_ps_e"):
            return name, comp

    raise RuntimeError("No zynq_ultra_ps_e instance found in BD")


def extract_config(comp: dict) -> dict[str, str]:
    """Map parameter name -> string value; keys become CONFIG.<name>."""
    params = comp.get("parameters") or {}
    if not isinstance(params, dict):
        raise RuntimeError("PS component parameters is not a dict")

    out: dict[str, str] = {}
    for name, entry in params.items():
        if isinstance(entry, dict):
            if "value" not in entry:
                continue
            value = entry["value"]
        else:
            value = entry
        # BD stores bare names; Vivado set_property uses CONFIG.*
        key = name if str(name).startswith("CONFIG.") else f"CONFIG.{name}"
        out[key] = "" if value is None else str(value)
    return out


def tcl_brace(s: str) -> str:
    """Quote a Tcl word with braces; escape embedded braces if needed."""
    if "{" not in s and "}" not in s and "\\" not in s:
        return "{" + s + "}"
    # Rare path: escape backslash and use quotes with backslash escapes.
    escaped = (
        s.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("$", "\\$")
        .replace("[", "\\[")
        .replace("]", "\\]")
    )
    return f'"{escaped}"'


def emit_tcl(configs: dict[str, str], instance_hint: str) -> str:
    lines: list[str] = [HEADER.rstrip(), ""]
    lines.append(f"# Instance in source BD: {instance_hint}")
    lines.append(f"# CONFIG property count: {len(configs)}")
    lines.append("")
    lines.append("proc apply_ps_preset {cell} {")
    lines.append("  if {$cell eq \"\"} {")
    lines.append('    error "apply_ps_preset: cell is empty"')
    lines.append("  }")
    lines.append("")

    items = sorted(configs.items(), key=lambda kv: kv[0])
    for chunk_idx, start in enumerate(range(0, len(items), CHUNK_SIZE)):
        chunk = items[start : start + CHUNK_SIZE]
        lines.append(f"  # CONFIG chunk {chunk_idx + 1}")
        lines.append("  set_property -dict [list \\")
        for key, val in chunk:
            lines.append(f"    {key} {tcl_brace(val)} \\")
        lines.append("  ] $cell")
        lines.append("")

    lines.append("  return $cell")
    lines.append("}")
    lines.append("")
    return "\n".join(lines)


def main(argv: list[str]) -> int:
    if len(argv) < 2:
        print(
            "usage: python scripts/extract_ps_preset.py <path/to/design_1.bd>",
            file=sys.stderr,
        )
        return 2
    bd_path = Path(argv[1])
    if not bd_path.is_file():
        print(f"error: BD not found: {bd_path}", file=sys.stderr)
        return 1

    with bd_path.open(encoding="utf-8") as f:
        data = json.load(f)

    name, comp = find_ps_component(data)
    configs = extract_config(comp)
    if not configs:
        print("error: no parameters extracted", file=sys.stderr)
        return 1

    tcl = emit_tcl(configs, name)
    OUT_TCL.write_text(tcl, encoding="utf-8", newline="\n")
    print(f"Wrote {OUT_TCL} ({len(configs)} CONFIG properties from {name})")
    print(f"Source BD: {bd_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
